[main] Update dependencies from dotnet/roslyn (#8236)
* Update dependencies from https://github.com/dotnet/roslyn build 20221208.26

Microsoft.Net.Compilers.Toolset
 From Version 4.4.0-2.22458.3 -> To Version 4.5.0-2.22608.26

* Un-ref InternableString.Simple

This triggered some C# compiler errors with newer versions of the
compiler:

```
S:\msbuild\src\StringTools\InternableString.Simple.cs(130,39): error CS8170: Struct members cannot return 'this' or other instance members by reference [S:\msbuild\src\StringTools\StringTools.csproj::TargetFramework=net35]
S:\msbuild\src\StringTools\InternableString.Simple.cs(130,20): error CS8347: Cannot use a result of 'InternableString.Enumerator.Enumerator(ref InternableString)' in this context because it may expose variables referenced by parameter 'spanBuilder' outside of their declaration scope [S:\msbuild\src\StringTools\StringTools.csproj::TargetFramework=net35]
```

Since this implementation is purely for the MSBuildTaskHost net35
compatibility case and self-describes as "inefficient", I think it's ok
to make it a regular non-ref struct.

Co-authored-by: dotnet-maestro[bot] <dotnet-maestro[bot]@users.noreply.github.com>
Co-authored-by: Rainer Sigwald <raines@microsoft.com>