Add nuget reference to System.Reflection.Metadata for XMakeTasks
AssemblyDependency/AssemblyInformation.cs(16,25): error CS0234: The type or namespace name `PortableExecutable' does not exist in the namespace `System.Reflection'. Are you missing an assembly reference? [/Users/ankit/dev/msbuild/src/XMakeTasks/Microsoft.Build.Tasks.csproj]
AssemblyDependency/AssemblyInformation.cs(17,25): error CS0234: The type or namespace name `Metadata' does not exist in the namespace `System.Reflection'. Are you missing an assembly reference? [/Users/ankit/dev/msbuild/src/XMakeTasks/Microsoft.Build.Tasks.csproj]
AssemblyDependency/AssemblyInformation.cs(383,61): error CS0246: The type or namespace name `MetadataReader' could not be found. Are you missing an assembly reference? [/Users/ankit/dev/msbuild/src/XMakeTasks/Microsoft.Build.Tasks.csproj]
AssemblyDependency/AssemblyInformation.cs(383,84): error CS0246: The type or namespace name `CustomAttribute' could not be found. Are you missing an assembly reference? [/Users/ankit/dev/msbuild/src/XMakeTasks/Microsoft.Build.Tasks.csproj]