Update System.Collections.Immutable to 5.0.0 (#5879)
Roslyn did this in vs16.8 but we didn't match it. This causes a failure in tasks that use Roslyn in-proc:

An exception was thrown while trying to compile the transformation code. The following Exception was thrown:
System.MissingMethodException: Method not found: 'System.Collections.Immutable.ImmutableDictionary2<!!0,!!1> System.Collections.Immutable.ImmutableDictionary.ToImmutableDictionary(Builder<!!0,!!1>)'.
   at Microsoft.CodeAnalysis.CSharp.SyntaxAndDeclarationManager.AddSyntaxTrees(IEnumerable1 trees)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.AddSyntaxTrees(IEnumerable1 trees)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonAddSyntaxTrees(IEnumerable1 trees)
   at Microsoft.VisualStudio.TextTemplating.CompilerBridge.PrepareNewCompilation()
   at Microsoft.VisualStudio.TextTemplating.CompilerBridge.Compile()
   at Microsoft.VisualStudio.TextTemplating.TransformationRunner.Compile(String source, String inputFile, IEnumerable1 references, Boolean debug, SupportedLanguage language, String compilerOptions). Line=0, Column=0