Update .NET Framework references to 9.0.0 (#11145)
* Update .NET Framework references to 9.0.0

* OK fine update sourcebuild too

* fixup! OK fine update sourcebuild too

* fixup! OK fine update sourcebuild too

* Add new dependencies

* Formats.Nrbf depends on Bcl.HashCode

* Don't ngen S.Resources.Extensions

This is ngen-ing in vsn context but it shouldn't
ever be used from the amd64 directory; that copy is for compat with
badly-written API users only.

* SRE pkgdef version bump too

* Official Build MpPreference workaround (#11464)

Try disabling AV in the official build script to avoid build breaks that manifest as

```
D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\9.0.0-beta.24516.2\tools\Sign.proj(72,5): error MSB4018: The "Microsoft.DotNet.SignTool.SignToolTask" task failed unexpectedly.
System.Runtime.Serialization.SerializationException: Type 'System.AssemblyLoadEventArgs' in assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' is not marked as serializable.
   at Microsoft.Build.BackEnd.Components.RequestBuilder.AssemblyLoadsTracker.CurrentDomainOnAssemblyLoad(Object sender, AssemblyLoadEventArgs args)
   at System.AppDomain.OnAssemblyLoadEvent(RuntimeAssembly LoadedAssembly)
   at Microsoft.Build.Framework.ITask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() [D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\9.0.0-beta.24516.2\tools\Sign.proj]
```

---------

Co-authored-by: Jan Provaznik <janprovaznik@microsoft.com>

* Add DiagnosticSource to SB baseline

* One DiagnosticSource

---------

Co-authored-by: Jan Provaznik <janprovaznik@microsoft.com>