Fix MSBuildEventSource (#13030)
I'm seeing this exception:

```
System.TypeInitializationException: The type initializer for 'Microsoft.Build.Eventing.MSBuildEventSource' threw an exception.
---> System.MissingMethodException: Method not found: 'Void System.Diagnostics.Tracing.EventSource..ctor(System.String, System.Guid)'.
   at Microsoft.Build.Eventing.MSBuildEventSource..ctor()
   at Microsoft.Build.Eventing.MSBuildEventSource..ctor()
   at Microsoft.Build.Eventing.MSBuildEventSource..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Build.Graph.ProjectGraph.<>c__DisplayClass41_0.<.ctor>g__BeginMeasurement|1()
   at Microsoft.Build.Graph.ProjectGraph..ctor(IEnumerable`1 entryPoints, ProjectCollection projectCollection, ProjectInstanceFactoryFunc projectInstanceFactory, Int32 degreeOfParallelism, CancellationToken cancellationToken)
   at Microsoft.Build.Graph.ProjectGraph..ctor(IEnumerable`1 entryPoints, ProjectCollection projectCollection, ProjectInstanceFactoryFunc projectInstanceFactory)
```

In ILSpy I see Microsoft.Build.Framework.dll
`18.3.0-preview-26055-101+e64f84d6312cdaf227d26aeabfa4817862404d59`
having:

```cs
    private MSBuildEventSource()
        : base("Microsoft-Build", new Guid(3561627800u, 33311, 22536, 76, 234, 30, 36, 233, 130, 202, 55))
    {
    }
```

But in `C:\Program
Files\dotnet\shared\Microsoft.NETCore.App\10.0.1\System.Private.CoreLib.dll`
(loaded in .NET 10) I see:

```cs
internal EventSource(Guid eventSourceGuid, string eventSourceName)
    : this(eventSourceGuid, eventSourceName, EventSourceSettings.EtwManifestEventFormat)
{
}
```

It's both internal and the args are backwards...
 
I believe this was introduced in #12886.
 
Which pulls in this change:
https://github.com/dotnet/runtime/pull/121180
 
That seems to introduce a source generator which calls the internal ctor
of EventSource (and with different order). As that's internal to .NET, I
expect it was not intended to be applied here in MSBuild.

This change simply reverts the change to `MSBuildEventSource`.

Co-authored-by: AR-May <67507805+AR-May@users.noreply.github.com>