Add missing using
Official build is failing with

    error CS0103: The name 'OutOfProcServerNode' does not exist in the current context

Co-authored-by: Dustin Campbell <dustin@teamcampbell.org>