Disable FEATURE_RTLMOVEMEMORY for mono builds
Commit 63cf735deb821969cb096056c0c429c78cc76fbb introduced use of
`RtlMoveMemory`, with the intention to use it only on full framework,
but missed disabling it in dir.props .

This manifested as:

```
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
System.EntryPointNotFoundException: GetEnvironmentStrings
  at (wrapper managed-to-native) Microsoft.Build.Internal.CommunicationsUtilities:GetEnvironmentStrings ()
  at Microsoft.Build.Internal.CommunicationsUtilities.GetEnvironmentCharArray () [0x00007] in <04b748a45d6742ba88de6a1fabdd4609>:0
  at Microsoft.Build.Internal.CommunicationsUtilities.GetEnvironmentVariables () [0x00011] in <04b748a45d6742ba88de6a1fabdd4609>:0
  at Microsoft.Build.Internal.Utilities.GetEnvironmentProperties () [0x00001] in <04b748a45d6742ba88de6a1fabdd4609>:0
  at Microsoft.Build.Evaluation.ProjectCollection.get_EnvironmentProperties () [0x0001f] in <04b748a45d6742ba88de6a1fabdd4609>:0
  at Microsoft.Build.Evaluation.ProjectCollection.InitializeToolsetCollection (Microsoft.Build.Evaluation.ToolsetRegistryReader registryReader, Microsoft.Build.Evaluation.ToolsetConfigurationReader configReader) [0x00011] in <04b748a45d6742ba88de6a1fabdd4609>:0
  at Microsoft.Build.Evaluation.ProjectCollection..ctor (System.Collections.Generic.IDictionary`2[TKey,TValue] globalProperties, System.Collections.Generic.IEnumerable`1[T] loggers, System.Collections.Generic.IEnumerable`1[T] remoteLoggers, Microsoft.Build.Evaluation.ToolsetDefinitionLocations toolsetDefinitionLocations, System.Int32 maxNodeCount, System.Boolean onlyLogCriticalEvents) [0x0012b] in <04b748a45d6742ba88de6a1fabdd4609>:0
This is an unhandled exception in MSBuild Engine -- PLEASE OPEN A BUG AGAINST THE MSBUILD TEAM.
System.EntryPointNotFoundException: GetEnvironmentStrings
  at (wrapper managed-to-native) Microsoft.Build.Internal.CommunicationsUtilities:GetEnvironmentStrings ()
  at Microsoft.Build.Internal.CommunicationsUtilities.GetEnvironmentCharArray () [0x00007] in <04b748a45d6742ba88de6a1fabdd4609>:0
  at Microsoft.Build.Internal.CommunicationsUtilities.GetEnvironmentVariables () [0x00011] in <04b748a45d6742ba88de6a1fabdd4609>:0
  at Microsoft.Build.Internal.Utilities.GetEnvironmentProperties () [0x00001] in <04b748a45d6742ba88de6a1fabdd4609>:0
  at Microsoft.Build.Evaluation.ProjectCollection.get_EnvironmentProperties () [0x0001f] in <04b748a45d6742ba88de6a1fabdd4609>:0
  at Microsoft.Build.Evaluation.ProjectCollection.InitializeToolsetCollection (Microsoft.Build.Evaluation.ToolsetRegistryReader registryReader, Microsoft.Build.Evaluation.ToolsetConfigurationReader configReader) [0x00011] in <04b748a45d6742ba88de6a1fabdd4609>:0
  at Microsoft.Build.Evaluation.ProjectCollection..ctor (System.Collections.Generic.IDictionary`2[TKey,TValue] globalProperties, System.Collections.Generic.IEnumerable`1[T] loggers, System.Collections.Generic.IEnumerable`1[T] remoteLoggers, Microsoft.Build.Evaluation.ToolsetDefinitionLocations toolsetDefinitionLocations, System.Int32 maxNodeCount, System.Boolean onlyLogCriticalEvents) [0x0012b] in <04b748a45d6742ba88de6a1fabdd4609>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.EntryPointNotFoundException: GetEnvironmentStrings
  at (wrapper managed-to-native) Microsoft.Build.Internal.CommunicationsUtilities:GetEnvironmentStrings ()
  at Microsoft.Build.Internal.CommunicationsUtilities.GetEnvironmentCharArray () [0x00007] in <04b748a45d6742ba88de6a1fabdd4609>:0
  at Microsoft.Build.Internal.CommunicationsUtilities.GetEnvironmentVariables () [0x00011] in <04b748a45d6742ba88de6a1fabdd4609>:0
  at Microsoft.Build.Internal.Utilities.GetEnvironmentProperties () [0x00001] in <04b748a45d6742ba88de6a1fabdd4609>:0
  at Microsoft.Build.Evaluation.ProjectCollection.get_EnvironmentProperties () [0x0001f] in <04b748a45d6742ba88de6a1fabdd4609>:0
  at Microsoft.Build.Evaluation.ProjectCollection.InitializeToolsetCollection (Microsoft.Build.Evaluation.ToolsetRegistryReader registryReader, Microsoft.Build.Evaluation.ToolsetConfigurationReader configReader) [0x00011] in <04b748a45d6742ba88de6a1fabdd4609>:0
  at Microsoft.Build.Evaluation.ProjectCollection..ctor (System.Collections.Generic.IDictionary`2[TKey,TValue] globalProperties, System.Collections.Generic.IEnumerable`1[T] loggers, System.Collections.Generic.IEnumerable`1[T] remoteLoggers, Microsoft.Build.Evaluation.ToolsetDefinitionLocations toolsetDefinitionLocations, System.Int32 maxNodeCount, System.Boolean onlyLogCriticalEvents) [0x0012b] in <04b748a45d6742ba88de6a1fabdd4609>:0
  ```