Change IDE0055 (Fix Formatting) warning->message (#8630)
IDE0055 is currently too unspecific - opting out of it.

### Sample error:

```
C:\src\msbuild\src\Build.UnitTests\BackEnd\MSBuild_Tests.cs(796,59): error IDE0055: Fix formatting [C:\src\msbuild\src\Buil
d.UnitTests\Microsoft.Build.Engine.UnitTests.csproj::TargetFramework=net472]
```

(changed to message and not blocking the build after this change)