Enable logging instance properties in default text loggers (#5414)
Edits console logger such that various properties can be output in an error or warning message. The properties are determined by an item "outputProperties" defined by the project. Ex:

```
Program.cs(14,13): error CS0103: The name 'Consol' does not exist in the current context [C:\Users\t-laprin\source\repos\tester_app\tester_app\tester_app.csproj:: SchemaVersion=2.0 TargetFramework=netcoreapp3.0 ]
```

Fixes #3015.