Disable LASTEXITCODE check
This is failing for reasons I don't understand; optimistically
hoping that something downstream will clearly fail if this goes
wrong.

`
dotnet-install: Installation finished
The variable '0' cannot be retrieved because it has not been set.
System.Management.Automation.RuntimeException: The variable '0' cannot be retrieved because it has not been set.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
at InstallDotNetCli, D:\a\1\s\build\build.ps1: line 100
at Build, D:\a\1\s\build\build.ps1: line 197
at <ScriptBlock>, D:\a\1\s\build\build.ps1: line 411
at <ScriptBlock>, <No file>: line 1
Killing running build processes...
##[error]Cmd.exe exited with code '1'.