[test] Use test assemblies from test deployment ..
.. directory for !CoreCLR builds, same as for CoreCLR builds.
Running it from the Output directory causes:

xUnit.net Console Runner (64-bit .NET 4.6.57.0)
System.InvalidOperationException: Unknown test framework: could not find
xunit.dll (v1) or xunit.execution.*.dll (v2) in
/Users/ankit/dev/msbuild/bin/Debug-MONO/Output