Allow null SdkResult from SdkResolver.Resolve
The doc comment explicitly mentions returning null and the SDK can do
so, which caused a break in dotnet/dotnet#4579:

    src\sdk\src\Resolvers\Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver\WorkloadSdkResolver.cs(35,36): error CS8764: Nullability of return type doesn't match overridden member (possibly because of nullability attributes).