Un-ref InternableString.Simple
This triggered some C# compiler errors with newer versions of the
compiler:

```
S:\msbuild\src\StringTools\InternableString.Simple.cs(130,39): error CS8170: Struct members cannot return 'this' or other instance members by reference [S:\msbuild\src\StringTools\StringTools.csproj::TargetFramework=net35]
S:\msbuild\src\StringTools\InternableString.Simple.cs(130,20): error CS8347: Cannot use a result of 'InternableString.Enumerator.Enumerator(ref InternableString)' in this context because it may expose variables referenced by parameter 'spanBuilder' outside of their declaration scope [S:\msbuild\src\StringTools\StringTools.csproj::TargetFramework=net35]
```

Since this implementation is purely for the MSBuildTaskHost net35
compatibility case and self-describes as "inefficient", I think it's ok
to make it a regular non-ref struct.