Get Microsoft SDK paths from 32-bit registry
Fixes #7047.

These worked in 32-bit MSBuild because the values are placed only in the
32-bit registry.

```sh-session
❯ reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.8" /s
ERROR: The system was unable to find the specified registry key or value.

msbuild on frameworkpath-reg-wow [$+] via .NET v6.0.100
❯ reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.8" /s /reg:32

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.8
    InstallationFolder    REG_SZ    C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\
    ProductVersion    REG_SZ    4.8.03928
    ProductName    REG_SZ    Microsoft .NET Framework 4.8 SDK
    KitsInstallationFolder    REG_SZ    C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.8\WinSDK-NetFx40Tools
    ProductVersion    REG_SZ    4.8.03928
    ComponentName    REG_SZ    Microsoft .NET Framework 4.8 SDK
    InstallationFolder    REG_SZ    C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.8\WinSDK-NetFx40Tools-x64
    ProductVersion    REG_SZ    4.8.03928
    ComponentName    REG_SZ    Microsoft .NET Framework 4.8 SDK
    InstallationFolder    REG_SZ    C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.8\WinSDK-NetFx40Tools-x86
    ProductVersion    REG_SZ    4.8.03928
    ComponentName    REG_SZ    Microsoft .NET Framework 4.8 SDK
    InstallationFolder    REG_SZ    C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\
```